version: '3.9'

name: dpa
services:

  db:
    container_name: db
    image: mongo:6.0.3
    hostname: dpaDBServer
    environment:
      - MONGO_INITDB_DATABASE=blogger
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 8100:27017
    networks:
      - dpa-blogger

  api:
    container_name: api
    build: ./api
    ports:
      - 80:8080
    volumes:
      - ./api:/api
    networks:
      - dpa-blogger
    depends_on:
      - db

  blogger:
    container_name: blogger
    build: ./blogger
    ports: 
      - 81:1000
    volumes:
      - ./blogger:/vlt

networks:
  dpa-blogger:
    driver: bridge
    name: dpa-blogger

volumes:
  npm-cache: