version: '3.9'

services:

  db:
    image: mongo:6.0.3
    hostname: dpaDBServer
    environment:
      - MONGO_INITDB_DATABASE=blogger
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 8100:27017
    networks:
      - dpaNetwork

  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    networks:
      - dpaNetwork
    depends_on:
      - db

  blogger-front:
    build: ./frontend/blogger
    ports: 
      - 80:3000
    # volumes:
    #   - ./frontend/blogger:/DPA_VOLUME
    networks:
      - dpaNetwork
    depends_on:
      - db
      - backend



networks:
  dpaNetwork:

volumes:
  DPA_VOLUME: