version: '3.9'

services:

  db:
    image: mongo:6.0.3
    hostname: dpaDBServer
    environment:
      - MONGO_INITDB_DATABASE=blogger
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 8100:27017
    networks:
      - dpa-network

  backend:
    build: ./backend
    environment:
      - MONGO_INITDB_DATABASE=blogger
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 8081:8080
    volumes:
      - ./backend:/backend
    networks:
      - dpa-network
    depends_on:
      - db

  blogger:
    build: ./blogger
    ports: 
      - 81:1000
    volumes:
      - ./blogger:/vlt



networks:
  dpa-network:
    driver: bridge
    name: dpa-network

volumes:
  npm-cache: