version: '3.9'

services:

  db:
    image: mongo:6.0.3
    hostname: dpaDBServer
    environment:
      - MONGO_INITDB_DATABASE=blogger
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 8100:27017
    networks:
      - dpaNetwork

  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    networks:
      - dpaNetwork
    depends_on:
      - db

  blogger:
    build: ./blogger
    user: root
    ports: 
      - 80:3000
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./blogger:/vlt
    networks:
      - dpaNetwork
    depends_on:
      - db
      - backend



networks:
  dpaNetwork: