version: '3.9'

services:

  db:
    image: mongo:latest
    hostname: dpaDBServer
    environment:
      - MONGO_INITDB_DATABASE=blogger
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 8100:27017
    networks:
      - dpaNetwork

  backend:
    build: ./backend
    command: python3 -u app.py
    ports:
      - 8080:8080
    volumes:
      - .:/DPA_VOLUMES
    networks:
      - dpaNetwork

  frontend:
    build: ./frontend
    command: npm run dev
    ports: 
      - 80:3000
    networks:
      - dpaNetwork



networks:
  dpaNetwork: