version: '3.9'

services:

  dpa-db:
    container_name: dpa-db
    image: mongo:6.0.3
    hostname: dpaDBServer
    env_file:
      - ./db/.env
    ports:
      - 8100:27017
    networks:
      - dpa-blogger
    restart: always

  dpa-api:
    container_name: dpa-api
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    networks:
      - dpa-blogger
    depends_on:
      - dpa-db
    restart: always

  blogger:
    container_name: blogger
    build: ./blogger
    ports:
      - 81:1000
    volumes:
      - ./blogger:/vlt
    restart: always

networks:
  dpa-blogger:
    driver: bridge
    name: dpa-blogger

volumes:
  npm-cache:
