version: '3.9'

services:

  dpa-db:
    container_name: dpa-db
    image: mongo:6.0.3
    hostname: dpaDBServer
    env_file:
      - ./db/.env
    ports:
      - 8100:27017
    volumes:
      - dpa-db-volume:/data/db
    networks:
      - dpa-network
      - dpa-blogger
    restart: always

  dpa-api:
    container_name: dpa-api
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    networks:
      - dpa-network
      - dpa-blogger
    depends_on:
      - dpa-db
    restart: always

  dpa-proccessor:
    container_name: dpa-proccessor
    build: ./proccessor
    env_file:
      - ./proccessor/.env
    ports:
      - 9000:80
    networks:
      - dpa-network
    restart: always

  dpa-blogger:
    container_name: dpa-blogger
    build: ./blogger
    ports:
      - 81:1000
    restart: always

networks:
  dpa-network:
    driver: bridge
    name: dpa-network
  dpa-blogger:
    driver: bridge
    name: dpa-blogger

volumes:
  npm-cache:
  dpa-db-volume: